os: windows
language: sh
python: '3.7'
before_install:
- choco install python3 --version=3.7.5
- export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
install:
- python -m pip install -r requirements.txt
cache:
  directories:
  - /C/Python37
  - $HOME/AppData/Roaming/Python/Python37
before_cache:
  - find /C/Python37/Lib/ -name '*.pyc' -delete
script: python -m pytest --cache-clear tests
before_deploy: pyinstaller --name FluorescenceImaging-$TRAVIS_TAG-win64 --onefile --noconsole __main__.py
deploy:
  provider: releases
  api_key:
    secure: Voco/cspghmNoWl4MQE6Rb/V4CDhjFRTPLkNZlGlHLB0U2s6L7vnws/o8iN1YF9t/1n2XOBRCGBFLYWyrWr2wA2WdzYbEGOU/wN1J1uwW8JzWff+b29jDskgolsI+SNfxn3SCNGcH2ys2b9WiCsc68NKspuAhjChL7ZgT0nHZVaV5jrT2jzSJDNXolBkkt/BHC+r+2blhPsIprA8Am1wGXxEUrvQYliXNvmrhlVAKfkY2JxurprycJ+S2gLHWR+Y2pRrYIhK1O+oV0powfKGffSSYlvyUdYax2RfVrjOTllMzmgY7YLD1qNxU0uXK9KZXjm/1ETWDQEkFOc+GRa8g0MyoyVhVtHBEEQsHHnkYX6CUNuSczHi2AfvfWerMAXefvpMKODOUSgxjHWpYYFpPFT4dGipjfA6DlqB2IcoZ18JPmJM2zgssKt56i4h0J+2APvT6+oimQ5cvR9c/ao0WmVvuINK8urMU3e8+c7nsPvKzKUWJs9lJeeqNrYPLu8+4h7F/wyu1vVDeg5tfD30Z1YePKMmfJlVx6+5M/mDzFKiqKlmcQTCpk0rUa6818FU481Ohn4EzN/ZpNGg/Sr6ny9iVVF7qItFsR+aKpymNfO9DWHESR+a3kCAza2dj2BnVvI5Uj+qvZ1J6FuctM9IlNPtspsFqVMslR83p3gY0xY=
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  name: $TRAVIS_TAG
  draft: true
  on:
    tags: true
